### ISSUE TITLE
Support for SAS3008 adapter

### ISSUE THREAD

**Issue by Happy2C0de** [sleinen/diskonade#38]
bdsm-info should support next generation SAS3008 adapter to be suitable for these servers as well.

**Comment by sleinen** [comment]
Thanks for opening the issue, @Happy2C0de.  We have some systems with SAS3008 adapters as well, and found that replacing "sas2ircu" with "sas3ircu" was mostly sufficient to make the bsdm-info script work with those.  I have a scrappy version that I pushed to a new branch, 38_sas3008_support.  Feel free to try it out!

**Comment by sleinen** [comment]
I merged this, even though it generates ugly error messages when sas3ircu isn't installed—even when it's otherwise not required because sas2ircu is there and works fine.

**Comment by sleinen** [comment]
Oops, turns out I made a mistake in error handling that breaks LSI 2008 support. This needs fixing.
