### ISSUE TITLE
Add some SMART counters

### ISSUE THREAD

**Issue by hstaub** [sleinen/diskonade#42]
Some SMART counters are often interesting and could be added to the initial output of bdsm-info. Counters that were already used: Reallocated_Sector_Ct, Reallocated_Event_Count, Current_Pending_Sector.

**Comment by sleinen** [comment]
Thanks! Reallocated_Sector_Ct was _supposed_ to be printed out if non-zero.  But changes in the format of `smartctl -x` have broken that functionality over the years (without us noticing).  In #43, I updated the parser to recognize the new format, and also made it easier to add new vendor-specific attributes of interest.  The three you mentioned will now be included in script output (again).
